#include "polygon.h"
#include <QDebug>

polygon::~polygon(){}

void polygon::setPoints(QPoint* newPoints, int count)
{
    points = newPoints;
    pointCount = count;
}

void polygon::move(const int x, const int y)
{
    QPoint currentTopLeft = getIDLocation();
    float distanceX = x - currentTopLeft.x();
    float distanceY = y - currentTopLeft.y();

    for(int i = 0; i < pointCount; i++)
    {
       points[i].setX(points[i].x() + distanceX);
       points[i].setY(points[i].y() + distanceY);
    }
}

void polygon::draw(QPaintDevice *device)
{
    QPainter &painter = get_painter();
    painter.begin(device);

    QString IdString = construct_ID_String(shapeName, getID());
    get_painter().drawText(getIDLocation().x(), getIDLocation().y() - 5, IdString);

    painter.setPen(get_pen());
    painter.setBrush(get_brush());

    painter.drawPolygon(points, pointCount);

    painter.end();
}

QPoint polygon::getIDLocation()
{
    QPoint leftMostPoint = points[0];
    for(int i = 1; i < pointCount; i++)
    {
        leftMostPoint = getLeftMostPoint(leftMostPoint, points[i]);
    }

    return leftMostPoint;
}

QPoint polygon::getLeftMostPoint(QPoint p1, QPoint p2)
{
    int x, y;
    if(p1.x() < p2.x())
        x = p1.x();
    else
        x = p2.x();

    if(p1.y() < p2.y())
        y = p1.y();
    else
        y = p2.y();

    return(QPoint(x,y));
}

double polygon::calcPerimeter()
{
    //return sqrt(pow(end.x() - begin.x(), 2) - pow(end.y() - begin.y(), 2));
    double perimeter = 0;
    for(int i = 0; i < pointCount; i += 2)
    {
        // Gets the perimeter of the poly's unique points
        perimeter += sqrt(pow(points[i+1].x() - points[i].x(), 2) + pow(points[i+1].y() - points[i].y(), 2));
    }
    // Gets the perimeter of the final line between the poly's first and last point (this is generated by Qt)
    perimeter += sqrt(pow(points[pointCount - 1].x() - points[0].x(), 2) + pow(points[pointCount - 1].y() - points[0].y(), 2));
    return perimeter;
}

double polygon::calcArea()
{
    double accumulatingArea = 0;
    double finalArea = 0;
    // this formula gets a polygon's area - joey
    // .5 * |(x1 * y2 – x2 * y1) + (x2 * y3 – x3 * y2) + ... + (xn−1 * yn – xn * yn−1) + (xn * y1 – x1 * yn)|
    for(int i = 0; i < pointCount - 1; i++)
    {
        accumulatingArea += (points[i].x() * points[i+1].y()) - (points[i+1].x() * points[i].y());
    }

    finalArea = accumulatingArea + ((points[pointCount - 1].x() * points[0].y()) - (points[0].x() * points[pointCount - 1].y()));

    return .5 * abs(finalArea);
}

QString polygon::getShapeString()
{
    //Shape ID
    QString outputString = "\nShapeId: " + QString::number(getID());

    //ShapeType
    outputString += "\nShapeType: Polygon";

    //Shape Dimensions
    outputString += "\nShapeDimensions: ";
    for(int i = 0; i < pointCount; i++)
    {
        outputString += QString::number(points[i].x()) + ", ";
        outputString += QString::number(points[i].y());
        if(i != pointCount-1)
            outputString += ", ";
    }

    //Pen Color
    outputString += "\nPenColor: " + penColorName;

    //Pen Width
    outputString += "\nPenWidth: " + QString::number(get_pen().width());

    //Pen Style
    outputString += "\nPenStyle: " + penStyleName;

    //Pen Cap Style
    outputString += "\nPenCapStyle: " + penCapStyleName;

    //Pen Join Style
    outputString += "\nPenJoinStyle: " + penJoinStyleName;

    //Brush Color
    outputString += "\nBrushColor: " + brushColorName;

    //Brush Style
    outputString += "\nBrushStyle: " + brushStyleName + '\n';

    return outputString;
}
